version: '3'

services:
  puppet:
    hostname: puppet
    image: puppet/puppetserver
    ports:
      - 8140:8140
    environment:
      # DNS_ALT_NAMES must be set before starting the stack the first time,
      # and must list all the names under which the puppetserver can be
      # reached. 'puppet' must be one of them, otherwise puppetdb won't be
      # able to get a cert. Add other names as a comma-separated list
      - DNS_ALT_NAMES
      - PUPPETDB_SERVER_URLS=https://puppetdb:8081
    volumes:
      - ./code:/etc/puppetlabs/code/
      - ./puppet:/etc/puppetlabs/puppet/
      - ./serverdata:/opt/puppetlabs/server/data/puppetserver/

  puppetdb:
    hostname: puppetdb
    image: puppet/puppetdb
    environment:
      - PUPPETDB_DATABASE_CONNECTION=${PUPPETDB_DATABASE_CONNECTION}
      - PUPPETDB_USER=${PUPPETDB_USER}
      - PUPPETDB_PASSWORD=${PUPPETDB_PASSWORD}
    ports:
      - 8080
      - 8081
    depends_on:
      - puppet
    volumes:
      - ./puppetdb/ssl:/etc/puppetlabs/puppet/ssl/
