---
apiVersion: v1
kind: Service
metadata:
  name: puppet
  labels:
    app: pupperware
spec:
  ports:
    - port: 8140
  selector:
    app: pupperware
    svc: puppet
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppet-code-claim
  labels:
    app: pupperware
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppet-serverdata-claim
  labels:
    app: pupperware
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppet-puppet-claim
  labels:
    app: pupperware
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppet-hiera-claim
  labels:
    app: pupperware
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppet
  labels:
    app: pupperware
spec:
  selector:
    matchLabels:
      app: pupperware
      svc: puppet
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pupperware
        svc: puppet
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/hiera.yaml") . | sha256sum }}
    spec:
      hostname: puppet
      containers:
        - image: puppet/puppetserver
          name: puppet
          env:
            # necessary to set certname and server in puppet.conf, required by
            # puppetserver ca cli application
            - name: PUPPETSERVER_HOSTNAME
              value: puppet
            - name: DNS_ALT_NAMES
              value: puppet
            - name: PUPPETDB_SERVER_URLS
              value: https://puppetdb:8081
          ports:
            - containerPort: 8140
          volumeMounts:
            - name: puppet-code-storage
              mountPath: /etc/puppetlabs/code/
            - name: puppet-puppet-storage
              mountPath: /etc/puppetlabs/puppet/
            - name: puppet-serverdata-storage
              mountPath: /opt/puppetlabs/server/data/puppetserver/
            - name: puppet-hiera-storage
              mountPath: /hiera
            - name: hiera-volume
              mountPath: /etc/puppetlabs/puppet/hiera.yaml
              subPath: hiera.yaml
            - name: manifests-volume
              mountPath: /etc/puppetlabs/puppet/manifests/site.pp
              subPath: site.pp
            - name: eyamlpub-volume
              mountPath: /etc/puppetlabs/puppet/keys/public_key.pkcs7.pem
              subPath: public_key.pkcs7.pem
            - name: eyamlpriv-volume
              mountPath: /etc/puppetlabs/puppet/keys/private_key.pkcs7.pem
              subPath: private_key.pkcs7.pem
      volumes:
        - name: puppet-code-storage
          persistentVolumeClaim:
            claimName: puppet-code-claim
        - name: puppet-puppet-storage
          persistentVolumeClaim:
            claimName: puppet-puppet-claim
        - name: puppet-serverdata-storage
          persistentVolumeClaim:
            claimName: puppet-serverdata-claim
        - name: puppet-hiera-storage
          persistentVolumeClaim:
            claimName: puppet-hiera-claim
        - name: hiera-volume
          configMap:
            name: hiera-config
        - name: manifests-volume
          configMap:
            name: manifests-config
        - name: eyamlpub-volume
          configMap:
            name: eyamlpub-config
        - name: eyamlpriv-volume
          configMap:
            name: eyamlpriv-config
      initContainers:
        - name: git-clone
          image: alpine/git
          args:
            - clone
            - --single-branch
            - --
            - {{ .Values.hieradataurl }}
            - /hiera
          securityContext:
            runAsUser: 1
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: puppet-hiera-storage
              mountPath: /hiera
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: manifests-config
  namespace: default
data:
  site.pp: |
    hiera_include('classes')
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: r10k-config
  namespace: default
data:
  r10k.yaml: |
    :cachedir: '/var/tmp/r10k_cache'
    sources:
      repositories:
        remote: {{ .Values.puppeturl | quote }}
        basedir: '/code/environments'
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hiera-git-pull
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: git
            image: alpine/git
            args:
            - -C
            - /hiera
            - pull
            volumeMounts:
              - name: puppet-hiera-storage
                mountPath: /hiera
          restartPolicy: OnFailure
          volumes:
            - name: puppet-hiera-storage
              persistentVolumeClaim:
                claimName: puppet-hiera-claim
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: r10k-deploy
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: r10k
            image: puppet/r10k
            args:
            - deploy
            - environment
            - --config
            - /r10k.yaml
            volumeMounts:
              - name: r10k-volume
                mountPath: /r10k.yaml
                subPath: r10k.yaml
              - name: puppet-code-storage
                mountPath: /code
          restartPolicy: OnFailure
          volumes:
            - name: r10k-volume
              configMap:
                name: r10k-config
            - name: puppet-code-storage
              persistentVolumeClaim:
                claimName: puppet-code-claim
