apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppetboard
  labels:
    app: pupperware
spec:
  selector:
    matchLabels:
      app: pupperware
      svc: puppetboard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pupperware
        svc: puppetboard
    spec:
      hostname: puppetboard
      containers:
        - name: puppetboard
          image: "puppet/puppetboard:{{.Values.dockerImage.puppetboard.tag}}"
          imagePullPolicy: "{{.Values.dockerImage.puppetboard.pullPolicy}}"
          ports:
          env:
          - name: "PUPPETDB_HOST"
            value: "puppetdb"
          - name: "PUPPETDB_PORT"
            value: "8080"
          ports:
          - name: puppetboard
            containerPort: 8000
