---
apiVersion: v1
kind: Service
metadata:
  name: puppet
  labels:
    app: pupperware
spec:
  ports:
    - port: 8140
  selector:
    app: pupperware
    svc: puppet
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppet-code-claim
  labels:
    app: pupperware
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppet-serverdata-claim
  labels:
    app: pupperware
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: puppet-puppet-claim
  labels:
    app: pupperware
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppet
  labels:
    app: pupperware
spec:
  selector:
    matchLabels:
      app: pupperware
      svc: puppet
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pupperware
        svc: puppet
    spec:
      hostname: puppet
      containers:
        - image: puppet/puppetserver
          name: puppet
          env:
            # necessary to set certname and server in puppet.conf, required by
            # puppetserver ca cli application
            - name: PUPPETSERVER_HOSTNAME
              value: puppet
            - name: DNS_ALT_NAMES
              value: puppet
            - name: PUPPETDB_SERVER_URLS
              value: https://puppetdb:8081
          ports:
            - containerPort: 8140
          volumeMounts:
            - name: puppet-code-storage
              mountPath: /etc/puppetlabs/code/
            - name: puppet-puppet-storage
              mountPath: /etc/puppetlabs/puppet/
            - name: puppet-serverdata-storage
              mountPath: /opt/puppetlabs/server/data/puppetserver/
            - name: git-repo
              mountPath: /hiera
            - name: hiera-volume
              mountPath: /etc/puppetlabs/puppet/hiera.yaml
              subPath: hiera.yaml
            - name: r10k-volume
              mountPath: /etc/puppetlabs/puppet/r10k.yaml
              subPath: r10k.yaml
            - name: manifests-volume
              mountPath: /etc/puppetlabs/puppet/manifests/site.pp
              subPath: site.pp
      volumes:
        - name: puppet-code-storage
          persistentVolumeClaim:
            claimName: puppet-code-claim
        - name: puppet-puppet-storage
          persistentVolumeClaim:
            claimName: puppet-puppet-claim
        - name: puppet-serverdata-storage
          persistentVolumeClaim:
            claimName: puppet-serverdata-claim
        - name: git-repo
          emptyDir: {}
        - name: hiera-volume
          configMap:
            name: hiera-config
        - name: r10k-volume
          configMap:
            name: r10k-config
        - name: manifests-volume
          configMap:
            name: manifests-config
      initContainers:
        - name: git-clone
          image: alpine/git
          args:
            - clone
            - --single-branch
            - --
            - {{ .Values.hieradataurl }}
            - /hiera
          securityContext:
            runAsUser: 1
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: git-repo
              mountPath: /hiera
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hiera-config
  namespace: default
data:
  hiera.yaml: |
    :backends:
      - yaml
    :hierarchy:
      - role/%{::role}
      - common
    :yaml:
      :datadir: /hiera
      :extension: 'yaml'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: manifests-config
  namespace: default
data:
  site.pp: |
    hiera_include('classes')
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: r10k-config
  namespace: default
data:
  r10k.yaml: |
    :cachedir: '/var/tmp/r10k_cache'
    sources:
      repositories:
        remote: {{ .Values.puppeturl | quote }}
        basedir: '/etc/puppetlabs/code/environments'
